### ISSUE TITLE
CLI and file extensions

### ISSUE THREAD

**Issue by jojomi** [RH12503/Triangula#10]
I am doing this:

``` bash
IN=schach.jpg
JSON=fitness
SVG=schach

triangula run -img "${IN}" -out "${JSON}"
triangula render -in "${JSON}.json" -img "${IN}" -out "${SVG}"
```

It is a bit weird to me that "-out" on run is adding a .json file extension even if I put in "fitness.json" already. A fallback for adding the extension is nice, but imho it should check if it is supplied already (strings.HasSuffix). That way I could use $JSON for both commands in the above example.

**Comment by rh12503** [comment]
Thanks for bringing this up, I've added this feature into the latest CLI update!
