### ISSUE TITLE
How do I build from source?

### ISSUE THREAD

**Issue by Milo123459** [RH12503/Triangula#12]
Hi, I cloned this repo and ran go build and got this error:
```
no Go files in C:\Users\milo5\Desktop\GitHub\triangula
```
Any ideas on how I can build from source?

My antivirus doesn't let me download the gui so I'm trying to self build it. Thanks!

**Comment by ghost** [comment]
I don't believe this repo has a main function, so if you want the gui, you'll need to run `go build` on https://github.com/RH12503/Triangula-GUI or for the cli, you need to run `go build triangula/main.go` on https://github.com/RH12503/Triangula-CLI.

I'm not sure what's up with the Virus Scanner though. I ran the latest 2 versions (Windows, Linux, and Mac) against Virus Total and it didn't have a problem. If you could list your virus scanner, that'd be helpful for the author to be able to investigate.

**Comment by Milo123459** [comment]
Oh, thank you.

**Comment by rh12503** [comment]
Thanks @alexis-evelyn! Is your issue resolved now @Milo123459?

**Comment by jasikpark** [comment]
> I don't believe this repo has a main function, so if you want the gui, you'll need to run `go build` on https://github.com/RH12503/Triangula-GUI or for the cli, you need to run `go build triangula/main.go` on https://github.com/RH12503/Triangula-CLI.
> 
> I'm not sure what's up with the Virus Scanner though. I ran the latest 2 versions (Windows, Linux, and Mac) against Virus Total and it didn't have a problem. If you could list your virus scanner, that'd be helpful for the author to be able to investigate.

What does this repo contain exactly then?
