### ISSUE TITLE
Unable to run Triangula on Windows 10

### ISSUE THREAD

**Issue by ever-blogger** [RH12503/Triangula#17]
I had downloaded [v1.1.2](https://github.com/RH12503/triangula/releases/download/v1.1.2/triangula-windows-1.1.2.zip), but it's not able to run on Windows 10 (Version 20H2), would like to understand is there any tutorial for installtion?

**Comment by rh12503** [comment]
You should be able to open it after allowing it to run. Do any error messages appear, or does nothing just happen when you open it?

**Comment by ever-blogger** [comment]
Nope nothing prompt, but I have figured out why. It's due to incompatibility.
The issue has been resolved. Thanks.

![image](https://user-images.githubusercontent.com/63139255/117573945-53969200-b10d-11eb-9088-4043c490febb.png)

**Comment by rh12503** [comment]
Glad you've resolved the issue. Do you know if this problem could happen to anyone else on Windows 10 or if it's because of something on your system? It would be nice to fix this if it does affect everyone.

**Comment by ever-blogger** [comment]
I think it will happen for others too, as compatibility setting is disable by default.
I'm also wondering is there a need to wait for 100% on Fitness? Because nothing after I clicked Save when 99.98%
Probably is something related with pop-up because I'm not able to import the photo with by `click to select`, only managed to do it with drag & drop.

**Comment by rh12503** [comment]
You should be able to save regardless of the fitness - it just indicates how similar the shapes are to the original image (100% is impossible). 

I'll have to test it out myself, but the desktop app has been used by a lot of others so it's kind of strange that there haven't been issues previously. 

If possible, could you test [1.0](https://github.com/RH12503/triangula/releases/tag/v1.0) and see if the problems still occur? I know that the first version works on Windows.

**Comment by ever-blogger** [comment]
Not sure why this happen, no issue on [v1.1.2](https://github.com/RH12503/triangula/releases/download/v1.1.2/triangula-windows-1.1.2.zipl), but program is works with steps of workaround:

1. Unable to start issue, can resolved by Troubleshoot compatibility
2. Unable to Save or  'click to select' can be resolved by deselect 'Compatibility mode' after completed `1.` (Troubleshoot compatibility)
![image](https://user-images.githubusercontent.com/63139255/117659211-3f669980-b1ce-11eb-8ed6-46999d6c19a7.png)

**Comment by rh12503** [comment]
I've tested it out on Windows 10 and everything seems to work fine. Are you running the app as an administrator?

**Comment by rh12503** [comment]
I just tried running the compatibility troubleshooter, and I get all of your issues when I run the program using Windows 8. (But it's fine running it regularly)

**Comment by ever-blogger** [comment]
Yes, I opened the .exe file with administrator access, probably it's due to some setting on my device like what you mentioned. Nonetheless, I'm really enjoy the app.😊

**Comment by rh12503** [comment]
Glad you enjoy the app! 

I'm closing this issue now then, but I'll try to add something to the README to help anyone else. Thanks for opening this issue!
