### ISSUE TITLE
--reps CLI option does not work

### ISSUE THREAD

**Issue by geekoftheweek** [RH12503/Triangula#6]
Using the CLI version, it appears that the `-r` and `--reps` options are ignored, as well as the claimed default of 500 reps, since no matter whether I supply the options or not, the algorithm still proceeds beyond the supplied number and continues until killed with CTRL+C.

**Comment by geekoftheweek** [comment]
In hindsight, I may have misunderstood the purpose of the command line option.  I thought it would halt the program and exit after hitting a certain number of generations, but I'm realizing it may refer instead to how frequently to write the output file.

**Comment by rh12503** [comment]
Sorry for the confusion, the CLI runs forever, and `--reps` specifies how often the file is saved. I'll update the README when I have a chance. Please let me know if anything else is unclear with the CLI!
