### ISSUE TITLE
Ken Thompson Image

### ISSUE THREAD

**Issue by padams** [RH12503/Triangula#7]
Hi maintainers, the image of Ken Thompson that you are using cannot be included in this project under an MIT license as the underlying image is licensed under CC-BY-NC-SA. Please note that in your license docs along with proper attribution or remove it. Thanks.

**Comment by ggerganov** [comment]
Ken Thompson where? I see just a bunch of triangles 😄

**Comment by rh12503** [comment]
Sorry about that @padams, should I attribute [this link](https://www.facesofopensource.com/ken-thompson-3/) and should I include your name? I take this seriously and I'm willing to make any changes/remove it.

**Comment by padams** [comment]
The issue is that you can't distribute that image as part of the source under MIT. So I'll leave that to you how you want to handle (separate compliant license and attribution or removal).

**Comment by rh12503** [comment]
I've updated the README, does that look okay now?

**Comment by abilash-dash** [comment]
I leave thish

**Comment by padams** [comment]
I don't think so. If you want to keep the file in the project then you either need to change the license of the whole project to a license that is compatible with Cc-BY-NC-SA or you need to create a separate LICENSE file in the directory where the image is located that explains that that file is CC-BY-NC-SA with attribution etc.

Because that new LICENSE file is several dirs deep, it's customary to amend the project's main LICENSE file to explain that some files in other directories have other licenses. This prevents users from being caught off guard thinking everything in the project is MIT.

**Comment by rh12503** [comment]
I'm a bit busy so I'm going to delete that image for now. Again, I'm so sorry about the license issues!
