### ISSUE TITLE
Left Side of Image Appears to Have Slight Triangulation Bias

### ISSUE THREAD

**Issue by plynml-c** [RH12503/Triangula#8]
This project is amazing. Thank you for building and uploading it. The outputs are remarkable and it makes computers seem like magic to me again.

It appears Triangula is somewhat biased to render / use triangle budget on the left side of images. Parts of an image further to the left seem to resolve to better detail. Not sure if it works better to allow images to process far longer, but it seems to stop making a difference after a while.

I don't know if this is either known, an actual issue, or helpful to you. Again, thanks for building something so cool and even... inspiring.

Target Photo: https://en.wikipedia.org/wiki/USS_America_(CV-66)#/media/File:USS_America_(CV-66)_underway_in_the_Indian_Ocean_on_24_April_1983.jpg
Dimensions: 2586 x 1769
Size: 2.11 MB
Filetype: .PNG (I converted it PNG before using)

Default Settings, 1,000 Points
![image](https://user-images.githubusercontent.com/18249772/115916241-891b5a00-a442-11eb-9d69-0357c10bf308.png)

Default Settings, 2,000 Points
![image](https://user-images.githubusercontent.com/18249772/115916626-0b0b8300-a443-11eb-80bb-8ca5180e3ad3.png)

Target Photo: https://en.wikipedia.org/wiki/Mount_Rushmore#/media/File:Mount_Rushmore_detail_view_(100MP).jpg
Dimensions: 1588 x 1080
Size: 655 KB
Filetype: .jpg

Default Settings, 1,000 Points
![image](https://user-images.githubusercontent.com/18249772/115917008-9422ba00-a443-11eb-800d-e0f624082ece.png)

Default Settings, 2,000 Points
See the figure's detail on the far left (George Washington) vs the figure on the far right (Abraham Lincoln)
![image](https://user-images.githubusercontent.com/18249772/115917412-3642a200-a444-11eb-8071-9c8d7855c5f9.png)

**Comment by rh12503** [comment]
That's interesting! Have you tried flipping those images to see if the issue still occurs?

**Comment by rh12503** [comment]
Found the reason why! Turns out my mutation function is slightly bias towards negative values. I'll see what I can do to fix this. Thanks for bringing this up!

**Comment by rh12503** [comment]
Should be fixed now in the latest release!

**Comment by plynml-c** [comment]
Can confirm that fixed it. Images now seem to resolve to better detail in fewer generations as well! Super cool
